---
- name: "install app & tools."
  become: true
  become_method: sudo
  apt:
    name: ["nodejs", "npm", "python"]
    state: latest
  apt:  
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

